### ISSUE TITLE
Resolve SSR issue with react-tinacms-contentful

### ISSUE THREAD

**Issue by chrisdmacrae** [ourchurchhome/ourchurchhome.ca#20]
Currently the site is not building on the `feature/add-basic-homepage branch`  In dev mode, all routes render the default error page with no feedback. 

I suspect this is an error with `react-tinacms-contentful` but can’t get any feedback from next to hunt it down. 

## Steps to reproduce

1. Clone this repo
2. Clone the `tinacms/react-tinacms-contentful` repo at this path, relative the this repo: `../tinacms/react-tinacms-contentful` and check out the `feature/authentication-change` branch
3. Start the server by running `npm run dev` or `yarn dev`

## Expected Result

The app renders, or returns a useful error. 

## Debugging

This repo is setup for nodejs debugging via visual studio code. Press `f5` with this repo open in visual studio code, and run the `npm run dev` command via the debug toolbar.

**Comment by chrisdmacrae** [comment]
@ncphillips @mittonface can you take a look at this and see if you can hunt down what’s causing the error page to be rendered but hang?

Also don’t ask about the late night tag, I’m having a bout of terrible insomnia this week.

**Comment by logan-anderson** [comment]
@chrisdmacrae  is the reason you are using the `server.js`  instead of `next dev`

**Comment by logan-anderson** [comment]
When I run in dev mode using server.js I get it building the error page but nothing shows up in the browser.  When I run using next dev (no server.js) I get this error 
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

@chrisdmacrae Not sure if this is helpful or not (I also may have not linked the contentful package correctly )

**Comment by chrisdmacrae** [comment]
@logan-anderson this _is_ helpful. I never thought of using `next dev`.

Do you mind taking a little bit more time to run through the source code of the contentful package on `feature/change-authentication` to see if there's any stupid hooks implementations I'm missing?

If you remove the `TinaContentfulProvider` it stops doing this.

**Comment by chrisdmacrae** [comment]
This was caused by conflicting versions of react
